
platform :ios, '8.0'

target 'LBXScanDemo' do


pod 'KTScan/LBXNative', path:"../"
pod 'KTScan/LBXZXing', path:"../"
pod 'KTScan/UI', path:"../"
pod 'LBXZBarSDK','~> 1.3'
pod 'Toast', '~> 4.0.0'

end






